lerna.json, package.json, yarn.lock
Introduced lerna for managing versions and releases for our packages
=> feat: introduced lerna

.github/workflows/greetings.yml
=> chore(ci): add greetings action

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
=> chore(commit): add github templates

.github/workflows/create-release.yml
Fixed variable names for github name and email
=> fix: fixed incorrect secret variable names

libs/ui5-angular/content-density/index.ts, libs/ui5-angular/content-density/ng-package.json
closes #21 
Adds content density directive
=> feat: added content density directive

libs/ui5-angular/project.json
=> fix: added ui5-webcomponents.module.ts to cached files

libs/ui5-angular/package.json, libs/ui5-angular/schematics/ng-add/index.ts
None
Icon dependencies were missing
=> fix: added missing peer dependencies to the ui5-angular

README.md
Tried to get started with this library, and it was not working
3. Documentation and Example validations
-   [x] poor examples
-   [x] update `README.md`
=> (docs) Correct the module name in the README.md

libs/ui5-angular/i18n/i18n.service.ts
NA
This load language should be triggered after ui5 received the data
=> fix: fixed i18n load language trigger

libs/ui5-angular/package.json, libs/ui5-angular/schematics/ng-update/0.2.0-rc.0/index.ts, libs/ui5-angular/schematics/ng-update/migrations.json
closes #56
Added ng-update schematic, which will be syncing @ui5/* versions
=> feat: update migrations setup

libs/angular-generator/src/lib/ui5-webcomponents/generic-cva.ts
closes https://github.com/SAP/ui5-webcomponents-ngx/issues/95
This issue fixes the problem where forms are not updated
=> fix: add a fix for touched not being updated for reactive forms

package.json, yarn.lock
Should fix the issues with releasing. Old lerna was not compatible with the new prettier
=> chore: updated lerna to the latest version

libs/fundamental-styles/package.json, libs/ui5-angular-theming/package.json, libs/ui5-angular/package.json
The peer dependencies were wrong
=> fix: quick fix for peer dependencies

apps/documentation/src/app/stories/compat/table.stories.ts, apps/documentation/src/app/stories/fiori/illustratedmessage.stories.ts, libs/ui5-angular/__snapshots__/fiori-snapshot-test.spec.ts.snap, libs/ui5-angular/__snapshots__/main-snapshot-test.spec.ts.snap
Update Illustrated Message: stories
-  fix example with custom title and subtitle:
- add example Illustrated Message in Dialog:
=> chore: update ui5-illustrated-message story

libs/fundamental-styles/schematics/get-config.ts, libs/ui5-angular/schematics/get-config.ts, yarn.lock
=> fix: leftover migration

lerna.json
=> chore: fix versions in lerna

README.md
update README.md and link with Angular/webC support
=> docs: update README.md and link with Angular/webC support

libs/angular-generator/src/lib/angular-module-file.ts, libs/transformer/project.json, libs/transformer/tsconfig.lib.json, libs/ui5-schema-parser/src/lib/api-json-parser/get-components.ts
=> fix: build issues

apps/documentation/src/app/stories/ai/button.stories.ts, yarn.lock
=> docs: fix ai button API docs

apps/documentation/src/app/stories/ai/prompt-input.stories.ts
=> docs: add ai prompt input

libs/ui5-angular/README.md
=> docs: update README.md

package.json, yarn.lock
=> chore(deps): sync nx versions
